sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t diegofsousa/docker-and-react-ci-cd -f Dockerfile.dev .

script:
  - docker run -e CI=true diegofsousa/docker-and-react-ci-cd npm run test