sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t diegofsousa/docker-and-react-ci-cd -f Dockerfile.dev .

script:
  - docker run -e CI=true diegofsousa/docker-and-react-ci-cd npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-and-react-ci-cd"
  env: "DockerAndReactCiCd-env"
  bucket_name: "elasticbeanstalk-us-east-2-787054017306"
  bucket_path: "docker-and-react-ci-cd-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY